### ISSUE TITLE
It's not updating with the latest episodes of Flash, and Arrow, though Supergirl is there.

### ISSUE THREAD

**Issue by rleibman** [AceFire6/ordered-arrowverse#1]

**Comment by AceFire6** [comment]
Thanks for the heads up @rleibman :smile:
I looked at the data sources and I think I know what the issue is. I'll try and get a fix out by the weekend.

**Comment by rleibman** [comment]
Thank you... btw, the little page is awesome! Super useful! I've started numbering my shows with it, they all make so much more sense now! I get to enjoy all the little references they do to each other.

**Comment by AceFire6** [comment]
@rleibman Thank you for the feedback. It's much appreciated. I'm fairly certain I've fixed the issue. If you have any other issues or suggestions feel free to let me know.
