### ISSUE TITLE
Episode Order keeps changing??

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [AceFire6/ordered-arrowverse#111]
So I noticed whenever either an episode of Arrow or LoT is added, they keep changing positions with each other.  Like at first Arrow was before LoT, then when another episode is added  LoT would be before Arrow.  I noticed this when LoT S04E11  was switching places with Arrow S07E18.

Makes it quite frustrating when actually trying to watch in order.. and you come back to find out.. you probably watched it in the wrong order.

**Comment by AceFire6** [comment]
Hi @SaiyanOfDarkness. Sorry about that. That happens when the shows air on the same day. The best bet is to watch them in airing order until I figure out a way to set that up on the site 👍

(Sorry for the delayed response, life has been busy)

**Comment by neil-menghani** [comment]
I'll tackle this issue and try to make sure same-day episodes follow air order. Best bet may be to hardcode CW air schedule

**Comment by neil-menghani** [comment]
I’m working on a fix for this bug based on air schedule and should have a pull request by later today. Do you have any other ideas/suggestion @acefire6

**Comment by AceFire6** [comment]
This was solved in #135
