### ISSUE TITLE
Add Black Lightning (New DC Show)

### ISSUE THREAD

**Issue by anshgyl** [AceFire6/ordered-arrowverse#16]
Announced episodes of Season 1 till now:-
S01 E01 - The Resurrection -  16 January 2018
S01 E02 - Lawanda: The Book of Hope - 23 January 2018
S01 E03 - Lawanda: The Book of Burial - 30 January 2018
S01 E04 - Black Jesus - 7 February 2018
S01 E05 - Aches and Pains - 14 February 2018
S01 E06 - Vengeance - 21 February 2018
S01 E07 - The New Norm - 28 February 2018
S01 E08 - Revelations - No Air Date
S01 E09 - Little Black Lies - No Air Date
S01 E10 - Sins of the Father - No Air Date
S01 E11 - Rebellion in the Ranks - No Air Date
S01 E12 - In the Lion's Den - No Air Date

Sources:- [https://en.wikipedia.org/wiki/Black_Lightning_(TV_series)](https://en.wikipedia.org/wiki/Black_Lightning_(TV_series))
[http://www.imdb.com/title/tt6045840/](http://www.imdb.com/title/tt6045840/)

**Comment by AceFire6** [comment]
@anshgyl Thank you for letting me know. I'll get on it soon when I have time to update the site 😄

**Comment by anshgyl** [comment]
Thanks for the awesome work.
And forgot to mention another show of the Arrowverse:- **Freedom Fighters: The Ray**
6 Episodes aired on 8th December, 2017

Sources:- [http://arrow.wikia.com/wiki/Freedom_Fighters:_The_Ray](http://arrow.wikia.com/wiki/Freedom_Fighters:_The_Ray)
[https://en.wikipedia.org/wiki/Freedom_Fighters:_The_Ray](https://en.wikipedia.org/wiki/Freedom_Fighters:_The_Ray)
[http://www.imdb.com/title/tt5957358/](http://www.imdb.com/title/tt5957358/)

**Comment by AceFire6** [comment]
@anshgyl I've finally got around to adding the new shows! Unfortunately, for now, I won't be including Black Lightning unless you can think of a good reason I should include it.

This decision is based on the fact that it isn't part of the Arrowverse: https://en.wikipedia.org/wiki/Black_Lightning_(TV_series)#Connection_to_the_Arrowverse

**Comment by anshgyl** [comment]
https://www.youtube.com/watch?v=VsWy1DAINDc
According to this promo, Black Lightning is also a part of Arrowverse and there would soon be crossovers.

**Comment by AceFire6** [comment]
Seems correct. I'll add it

**Comment by cyphix333** [comment]
Hmmmm....... I think that's just a teaser of a possibility of it joining the Arrowverse.... maybe? I read it's not part of the Arrowverse and it's even filmed in a totally different location, making it hard for crossovers; but that doesn't mean it _won't_ be part if it in the future. Hmmmmmm.

**Comment by AceFire6** [comment]
Due to popular demand, I've decided that it should be added 👍
