### ISSUE TITLE
Episode Order is messed up again

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [AceFire6/ordered-arrowverse#194]
It was fine earlier, but now it seems to have changed.

![image](https://user-images.githubusercontent.com/24264268/73326089-98e3c880-4216-11ea-80c9-97b9e1335e37.png)

**Comment by SaiyanOfDarkness** [comment]
Supergirl and Batwoman episodes keep changing positions with each other as well.

**Comment by neil-menghani** [comment]
This is because the dictionary needs to be updated with the air schedule
for Spring 2020. It will have to be updated every season (since the order
can always change). I will update it and make a pull request.

Best,
Neil

**Comment by cogburnd02** [comment]
Since I'm suuuuper-behind & catching up (haven't seen Crisis on Infinite Earths at all, yet) where does the Black Lightning episode go? (Presumably LoT's pt. 5 comes after Arrow's pt. 4.---is that the only error here?)

**Comment by neil-menghani** [comment]
I believe Batwoman aired before Black Lightning so after pt.2 I guess.

**Comment by WORMSS** [comment]
Legends "Part Five" is listed before Arrow "Part Four"
