### ISSUE TITLE
Supergirl and Vixen season 2

### ISSUE THREAD

**Issue by panamarocker** [AceFire6/ordered-arrowverse#20]
There is a couple Supergirl episodes out of order. In addition, shouldn't Vixen season 2 be grouped together like season 1?

**Comment by AceFire6** [comment]
@panamarocker Sorry for not getting this issue sooner. The reason Vixen Season 1 is grouped as it is is because nothing else aired when it was airing.

Do you know which Supergirl episodes are out of order?

**Comment by jimbobwho** [comment]
I have been watching through following this list.  you have flash S02E18  versus Doom as item 178. unless I have missed something this is the first appearance of the tackion enhancer. this was previously seen in the cross over episode of supergirl s01e18 worlds finest that you have at 168 on this list. it may help sort out the order.

**Comment by jimbobwho** [comment]
Just got to 261, Supergirl s02e16 star-crossed, at the end it says to be continued in the flash. The next flash episode is 263, the flash s03e17 duet, which continues the story. You have legends of tomorrow, s02e15 fellowship of the spear, set as 262. this was aired on the same night as the aforementioned episode of the flash. May I suggest these two are swapped over.

**Comment by neil-menghani** [comment]
This issue of same-day episodes needing to be swapped should be resolved with #111

**Comment by AceFire6** [comment]
This was solved in #135
