### ISSUE TITLE
Freedom Fighters: The Ray

### ISSUE THREAD

**Issue by panamarocker** [AceFire6/ordered-arrowverse#21]
I know the list is going by date. However, I feel like "Freedom Fighters: The Ray" should go after "Arrow 5×23: Lian Yu" and before the new season. It would make more sense in the story.

**Comment by AceFire6** [comment]
Hey @panamarocker. Thanks for taking the time to make this issues. I'll look into it

**Comment by neil-menghani** [comment]
Since it the season was released on December 8, 2017 between the fall and midseason, for consistency sake it should remain after Season 6, Episode 9. This website purely follows release order, so the current order is correct.
