### ISSUE TITLE
wrong air date

### ISSUE THREAD

**Issue by mitchyboii** [AceFire6/ordered-arrowverse#211]
565 | DC's Legends of Tomorrow | S05E06 | Mr. Parker's Cul-De-Sac March 03, 2020 

It airs on March 10, 2020 according to the CW and their wiki :)
<img width="278" alt="Screen Shot 2020-03-07 at 3 30 01 AM" src="https://user-images.githubusercontent.com/61901745/76139994-f0e6c980-6023-11ea-8fe6-6aa0acd7304e.png">

**Comment by Marshal313** [comment]
It looks like site's data is not up to date.
I don't exactly know how it works and how it pulls data from Arrow Wiki.
But I've seen a "Build Failing" badge due to last commit. Maybe that's the reason !
