### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [AceFire6/ordered-arrowverse#296]
site isn't accessible

**Comment by AceFire6** [comment]
@SaiyanOfDarkness thanks, I've fixed the issue

**Comment by Bigmelwalter** [comment]
Site is still down as of 4:31AM USA Eastern Standard Time

**Comment by Bigmelwalter** [comment]
Site has internal error when filtering dates.

**Comment by AceFire6** [comment]
@Bigmelwalter I've fixed that issue now. Thanks for letting me know 👍
