### ISSUE TITLE
Other shows

### ISSUE THREAD

**Issue by MissTechnolysis** [AceFire6/ordered-arrowverse#5]
You should have added the other shows in the CW arrowverse to the list including Vixen, Constantine (animated + real life) and the other webshows).

**Comment by AceFire6** [comment]
@MissTechnolysis I'm definitely willing to add them. Do you have a link to a list of the shows you want to be added? Or their names?

**Comment by zoidbergwill** [comment]
This seems to mention most of them: https://en.wikipedia.org/wiki/Arrowverse

**Comment by MissTechnolysis** [comment]
Yes, what about adding phases to each season of arrow which corresponds with the growth of the Arrowverse. Season 1 was phase 1 with no multiverse included, then season 2 again with no multi-verse, then season 3 with Flash being added and then season 4 with supergirl, constantine, vixen and legends of tommorow being added then of course season 5 which is phase 5 with all four medias in balance.

**Comment by MissTechnolysis** [comment]
kind of like how Marvel does their phase 1, 2. 3 and 4 for each movie.

**Comment by Renusek** [comment]
@MissTechnolysis Vixen would be phase 3 then, not 4

And yes, Vixen and Constantine (and every new Arrowverse show) should be added to the list too.

**Comment by zoidbergwill** [comment]
PRs welcome. :trollface:

**Comment by AceFire6** [comment]
@Renusek fixed this in PR #6
