### ISSUE TITLE
Read from API via my Discord Bot

### ISSUE THREAD

**Issue by adrifcastr** [AceFire6/ordered-arrowverse#96]
Hey, I'm currently working on a Discord Bot, and I'm having quite some trouble in calling your RSS feed. Either because I'm just dumb or because I'm having trouble calling the atom feed, I'd appreciate any type of response.

**Comment by AceFire6** [comment]
Hi @adrifcastr. That's really cool! What issues are you having? The last time I checked the feed it was working okay (at least according to a few browser plugins). Let me know if you still need help!

(Sorry for the delayed response, life has been busy)

**Comment by adrifcastr** [comment]
> 
> 
> Hi @adrifcastr. That's really cool! What issues are you having? The last time I checked the feed it was working okay (at least according to a few browser plugins). Let me know if you still need help!
> 
> (Sorry for the delayed response, life has been busy)

hey, thanks for the answer, yeah well, so my issue is that the RSS feed is well not an API obviously, it'd be really great if you could implement a structured api e.g. [https://api.urbandictionary.com/v0/define?term=hello%20world](url) that accepts terms, so that bot/voice commands could return the corresponding line

**Comment by AceFire6** [comment]
@adrifcastr I can probably do that. What sorta terms should it accept?

**Comment by adrifcastr** [comment]
> @adrifcastr I can probably do that. What sorta terms should it accept?

that'd be awesome (the api usage will obviously be credited with "powered by arrowverse.info")
I think the best would be very simply the currently airing shows so
"flash"; "arrow"; "lot/"legends"; "supergirl";"batwoman";
and then simply have the json have the rss contents like
"title":The Flash S06E02
"airdate": The Flash S06E02 - The Flash of the Lightning will air on <airdate>

or whatever you think would be appropriate, either way an api would be super useful and much appreciated!

**Comment by AceFire6** [comment]
Hi @adrifcastr. I finally got around to building the API endpoint. The plan is to release it today. Let me know if it's suitable. I don't mind iterating on it from here.

I'm hoping to shore up the list and get the ordering right in the next two weeks using a database and at that point, the data will be in a much more malleable format.

**Comment by adrifcastr** [comment]
Thanks, I'll check it out this week and get back to you, keep up your work mate, it's greatly appreciated!

**Comment by adrifcastr** [comment]
@AceFire6 I successfully implemented reading from the API, thanks a bunch, you can find the code [here](https://github.com/adrifcastr/Gideon/blob/master/cmds/next.js) and your credit in the [readme](https://github.com/adrifcastr/Gideon) and within the bot's response aswell.
